# Generated by Django 3.2.16 on 2022-10-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='seL3rcnvhM', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
