# Generated by Django 3.2.16 on 2022-10-24 19:58

from django.db import migrations, models
import snapzapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapzapp', '0002_auto_20221024_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=snapzapp.models.idGenerator, max_length=30, unique=True),
        ),
    ]
